### ISSUE TITLE
CHF

### ISSUE THREAD

**Issue by Landsberger** [bengourley/currency-symbol-map#12]
Great map, guys!  Just FYI, the one symbol you are missing, the Swiss franc (CHF) is commonly abbreviated Fr in Switzerland.

**Comment by bengourley** [comment]
Hi, thank you :smile: Do you live/spend a lot of time in Switzerland? If so, which would you say is more commonly displayed, `Fr` or `CHF`?

We already have it in the map as `CHF` but I will change it if you know that `Fr` is more common.
