### ISSUE TITLE
bower install currency-symbol-map

### ISSUE THREAD

**Issue by k-funk** [bengourley/currency-symbol-map#14]
Are you open to PR's to allow `bower install`ing currency-symbol-map? I'd like to use this package in-browser.

Someone forked this repo a few months back: https://github.com/rhodgkins/currency-symbol-map/tree/bower, though it needs a little cleanup.

**Comment by bengourley** [comment]
Hi, yeah I'm fine with people installing this with bower. What needs to happen? Just a bower.json? If you could make a PR that would be excellent as I personally don't use it.

**Comment by k-funk** [comment]
https://github.com/bengourley/currency-symbol-map/pull/17

**Comment by k-funk** [comment]
I forgot that `require` isn't a part of browsers, so currency-symbol-map still can't be used in-browser. 

There's a couple approaches to get a currency-symbol-map.min.js installed via bower.

1. Include `currency-symbol-map.min.js` in this repo, that gets built by something like Grunt, but has to be (or at least should be) manually built every time a new version is released. [backbone](https://github.com/jashkenas/backbone) uses this approach.
2. Make a separate repo that's a shim for building/installing. [jquery](https://github.com/jquery/jquery-dist) and [highlightjs](https://github.com/components/highlightjs) do this.

I'd say we either move forward with one of these, or alternatively, remove `bower.json` that was recently included since it's currently useless to the front end :(

**Comment by k-funk** [comment]
👍
