### ISSUE TITLE
Symbol left or right?

### ISSUE THREAD

**Issue by alextrastero** [bengourley/currency-symbol-map#16]
Would be great if you could get a symbol object with say `{left: '', right: '€'}` or `{left: '£', right: ''}`. So you could write:
`getSymbolFromCurrency('GBP'); //=> {left: '£', right: ''}`

**Comment by bengourley** [comment]
This sounds like a great idea!

**Comment by bestan** [comment]
I'd suggest introducing a new method like ```getSymbolFromCurrencyWithExtras``` that returns ```{symbol: '£', position: 'left', ...}```. This approach would allow adding additional settings.

**Comment by alextrastero** [comment]
Yeah, 👍  for additional settings but I'm not sure the position attribute would be enough, take for example `AUD`:
```
getSymbolFromCurrencyWithExtras('AUD'); //=> { left: '$', right: 'AU', ... }
```

**Comment by bestan** [comment]
@alextrastero can you link to such examples? I'm seeing that Australians often use ```AU $20```, instead of ```$20AU```.

It might be a good idea to return format, i.e. ```{symbol: '£', format: '£%f'}```

**Comment by alextrastero** [comment]
http://www.airbnb.com in footer select currency: AUD :-)

**Comment by bengourley** [comment]
I'm concerned that there are multiple acceptable formats in some contexts.

**Comment by bestan** [comment]
True. It would be quite difficult to support.

@alextrastero I'd recommend looking at https://www.npmjs.com/package/globalize#currency-module for a more advanced solution.

**Comment by bengourley** [comment]
Closing because this would add complexity and/or opinion. KISS here :)
