### ISSUE TITLE
Package pulled from npm is missing "TRY" symbol

### ISSUE THREAD

**Issue by AshCoolman** [bengourley/currency-symbol-map#19]
I have zero idea why

Tried on OSX 10.11.5 and and on Ubuntu Ubuntu 14.04.4 LTS vagrant (hosted by osx)

```
$ npm --version
3.9.5
```

ping me if you want more details.

Thanks

**Comment by bengourley** [comment]
Sorry, somebody only recently added the symbol for TRY. Their pull request was merged but I didn't publish a new version. I've just published v3.0.1 to npm and it should contain TRY now. Cheers  🇹🇷
