### ISSUE TITLE
3.1.0 tagged release does not have latest map

### ISSUE THREAD

**Issue by natation** [bengourley/currency-symbol-map#25]
It doesn't seem like v3.1.0 tagged release has the latest map. i.e. latest master map has BHD, but 3.1.0 tagged release does not have it. Please let me know. Thanks!

**Comment by bengourley** [comment]
yeah I need to remove the reverse lookup functionality as per #23 before I cut another release

**Comment by gnbonney** [comment]
Any update?

**Comment by mecorusfc** [comment]
Ben, when do you expect to do another release?

**Comment by bengourley** [comment]
Major version (`4.0.0`) published.

Sorry for the delay. See the [readme](https://github.com/bengourley/currency-symbol-map) for the changelog.
