### ISSUE TITLE
Some symbols are different with XE

### ISSUE THREAD

**Issue by weliame** [bengourley/currency-symbol-map#31]
Hi team,

This repo is really helpful for me. Thank you guys. Found a small issue, seems some symbols are different with XE, please see following list,

Code       | Symbol here  | Symbol in XE 
--------- | ------------- | -------------
AZN         | ₼                    | ман
BOB         | Bs.                 | $b
CHF         | Fr.                  | CHF 
KZT         | ₸                    | лв

**Comment by bengourley** [comment]
Hi @weliame. Are you familiar with any of these currencies? Do you know if the symbols we have are incorrect, or just that there are multiple correct versions?

I know for example that "CHF" and "Fr." are both correct, and that CHF is preferred. It looks like I unintentionally changed that when I merged this commit 3cf532fd2bc78a51c389ac2c76d263e9596bb78f.

Pull request welcome!

**Comment by weliame** [comment]
Hi @bengourley , thanks for your response. Honestly say that I'm not familiar with those currencies. I just compared the XE symbols with the map file and found some differences. And symbols here are definitely correct according to https://en.wikipedia.org/wiki/ISO_4217. I get message from `Readme.md` that Currency symbols originally sourced from xe, so I provide the differences part info here.

**Comment by bengourley** [comment]
Ok. I will make a note to update these.

The original list was sourced from XE but various people have contributed missing currencies and also updated symbols. You can see the contributed updates here: https://github.com/bengourley/currency-symbol-map/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged
