### ISSUE TITLE
Throwing a TypeError when input isn't string

### ISSUE THREAD

**Issue by LinusU** [bengourley/currency-symbol-map#36]
How about throwing a TypeError when input isn't a string? Currently `getSymbolFromCurrency(1)` returns undefined, but it seems very likely that it would only be due to programmer error that something non-string was submitted.

I'd be happy to submit a PR if you want it 🙌

**Comment by bengourley** [comment]
> it would only be due to programmer error

it could also be bad data retrieved from the database! I intentionally return `undefined` rather than throwing so that the programmer doesn't **have** to catch errors. As a user you can opt _in_ to checking `undefined`, but you can't opt _out_ of `try/catch`. Thanks for the suggestion though :)
