### ISSUE TITLE
ES6 modules import within a native ES modules library, Rollup setup

### ISSUE THREAD

**Issue by revelt** [bengourley/currency-symbol-map#39]
hi guys!

Has anybody been able to successfully consume this library in another, native ES modules-code library? I quickly browsed through dependents on npm but none seem to be natively in ES modules.

I'm rewriting [one](https://github.com/codsen/csv-sort) of my libs that consumes this library to be in ES modules and I'm having trouble with Rollup. It does not recognise `currency-symbol-map/map (imported by src/util.js)` (**as per readme instructions**):

![screen shot 2017-11-12 at 21 10 10](https://user-images.githubusercontent.com/8344688/32703621-63432ee8-c7f0-11e7-976a-28e5ae537f77.png)

I am following the readme instructions though, `import currencyToSymbolMap from 'currency-symbol-map/map'`

Looking at the setup of this library, I find it strange. Correct me if I'm wrong, but in order to properly support ES modules library should be **rewritten in ES modules** and end-file path to be wired up to `module` key in `package.json`. For that you need Rollup and Babel plugin and transpile a copy to CommonJS and wire up as `main` in `package.json`.

For a proper ES modules setup it's not enough just to wire it up via `module.exports` in main JS file, is it?

---

For the record I'm not a Rollup n00b, I have published whole chains of open source native ES module [libraries](https://github.com/codsen/ast-monkey) consuming other [libraries](https://github.com/codsen/ast-compare/) and I'm following Rollup [template](https://github.com/rollup/rollup-starter-lib/tree/babel). If I can't get it working others probably can't either (or they probably haven't jumped onto ES modules bandwagon yet).

---

On the positive side, that's an awesome library.

cheers
Roy

**Comment by bengourley** [comment]
Hey Roy. I accepted the ES module documentation as a PR (#28) and it was subsequently updated in this PR (#35). I personally don't use ES modules, so I would be happy to do any of the following options:

- receive a PR that fixes the docs
- receive a PR that makes it possible to import just the map with ES modules (and fixes the docs if required)
- remove the ES module documentation myself, as this module is written primarily for consumption by commonjs/node style module loaders

Let me know what you think!

**Comment by revelt** [comment]
Let's close, I can't confirm there is an issue any more. Thank you for looking into this 👍
