### ISSUE TITLE
Currency symbols displays as empty squares in chrome (windows only)

### ISSUE THREAD

**Issue by uniconstructor** [bengourley/currency-symbol-map#40]
I'm using this package at client-side as browser script via browserify.
It works fine for Linux and Mac (tested in chrome, safari and firefox), but Windows machines cannot recognize currency symbols, and it looks like this:

https://prnt.sc/hau1xj

I don't know how and why this happens, but if you have the same problem, you can try to use HTML entities instead of utf8 symbols.

Check out this gist - it contains currency codes mapped to the html entities: https://gist.github.com/Gibbs/3920259#gistcomment-2259740

**Comment by bengourley** [comment]
Is the charset specified on your page? Either:

- HTML tag in the `<head/>`: `<meta charset="UTF-8">` 
- HTTP header: `Content-Type: text/html; charset=utf-8`

My understanding is that some modern systems assume UTF-8 but some assume ASCII, so you need to explicitely declare the charset.

Other things to check (but assuming this isn't the case as it's working in other browsers)… do the characters for these code points exist in the font you are using? It may be the case that a different font is being used on different OSs.

**Comment by uniconstructor** [comment]
The charset of the page is UTF-8, and `script` tag encoding is also set to utf-8. Gulp bundler also uses utf-8. 
The idea about fonts sound good, but Browserify bunde cannot include static assets like fonts (only JS files). I can use webpack to create bundle with fonts - but switching entire project from browserify to webpack is overkill for my current task. I tried to use html entities and it solved my problem. 

Anyway, thank you for your reply.

**Comment by bengourley** [comment]
I'm not suggesting you bundle the font in with your JavaScript. That sounds like a terrible idea! (maybe my use of the term [code point](https://en.wikipedia.org/wiki/Code_point) misled you?)

I just wondered if the actual font that renders in Windows is the same as OSX/Linux, and if not it might not include all the currency symbols.

**Comment by uniconstructor** [comment]
Hello, Ben. Just a few words about this error: here is some kind of detective story :)
Our testers found what causes the problem.
The problem reproduces in Browserstack in **all** browsers **only** in Windows 7, and only for **ruble sign** (&#8381;).
Why?
Well... because the the Central Bank of Russia officially approved rouble sign [only in December 2013 (!)](https://en.wikipedia.org/wiki/Ruble_sign). Windows 7 released in 2009. It's propietary fonts does not contain the rouble sign and probably Microsoft doesn't care about update them. (windows 8 and 10 displays rouble sign correctly).

So - this is not problem of you lib, it's not problem of my code - it's all between Central Bank of Russia and Windows 7 - so leave 'em alone :)

Have a nice day.
