### ISSUE TITLE
Zambian Currency ZMK is missing

### ISSUE THREAD

**Issue by tomerb15** [bengourley/currency-symbol-map#43]
Zambian Currency ZMK is missing.
https://www.xe.com/currency/zmk-zambian-kwacha

**Comment by jasonenglish** [comment]
I don't think `ZMK` is the correct currency code for Zambia. It lists `ZMW` as the [most current Zambian currency](https://en.wikipedia.org/wiki/ISO_4217#Active_codes) code and `ZMK` in the [Historical currency codes](https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes)

The mapping doesn't list any Zambian currency, I think that might be the real issue?

Let me know if I missed something/reading it wrong.

**Comment by namenyi** [comment]
Fixed in https://github.com/bengourley/currency-symbol-map/pull/61
