### ISSUE TITLE
AUD symbol incorrect

### ISSUE THREAD

**Issue by Gnenc** [bengourley/currency-symbol-map#83]
https://github.com/bengourley/currency-symbol-map/blob/e952bf895ca6f8a549331f3f4f13e69ce8bf6d60/map.js#L9

should be AU$ instead of simple $
https://en.wikipedia.org/wiki/Australian_dollar

**Comment by namenyi** [comment]
Hello @Gnenc, thanks for raising it! 

The page you linked states these:

> Symbol	$

> The Australian dollar ([sign](https://en.wikipedia.org/wiki/Currency_sign): $; [code](https://en.wikipedia.org/wiki/ISO_4217): AUD) is the [currency](https://en.wikipedia.org/wiki/Currency) of [Australia](https://en.wikipedia.org/wiki/Australia), (...) it is almost always abbreviated with the [dollar sign](https://en.wikipedia.org/wiki/Dollar_sign) ($), with A$ or AU$ sometimes used to distinguish it from other [dollar](https://en.wikipedia.org/wiki/Dollar)-denominated currencies.

I find similar information in official sources too, signalling that $ is the primary symbol.

Based on these, I don't think it would be a good idea to push such a breaking change to the library.
